version: '3.8'
services:
  backend:
    image: sayan896/project-backend:latest
    ports:
      - "8000:8000"
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
  ollama:
    image: sayan896/project-ollama:latest
    ports:
      - "11434:11434"  
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 5
  frontend:
    image: sayan896/project-frontend:latest
    ports:
      - "8081:80"  
    environment:
      - BACKEND_URL=http://backend:8000
networks:
  default:
    driver: bridge
volumes:
  ollama-data: